# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: markdpwn 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "markdpwn".freeze
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Victor Costan".freeze]
  s.date = "2017-05-15"
  s.description = "HTML-formats text documents such as Markdown, textile, and source code".freeze
  s.email = "victor@costan.us".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".project",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/markdpwn.rb",
    "lib/markdpwn/code.rb",
    "lib/markdpwn/docs.rb",
    "lib/markdpwn/dpwn.rb",
    "lib/markdpwn/glue.rb",
    "lib/markdpwn/red_carpet_renderer.rb",
    "markdpwn.gemspec",
    "test/fixtures/readme.asciidoc",
    "test/fixtures/readme.md",
    "test/fixtures/readme.org",
    "test/fixtures/readme.pod",
    "test/fixtures/readme.rdoc",
    "test/fixtures/readme.rst",
    "test/fixtures/readme.textile",
    "test/fixtures/readme.wiki",
    "test/fixtures/view.html.erb",
    "test/helper.rb",
    "test/markdpwn/code_test.rb",
    "test/markdpwn/docs_test.rb",
    "test/markdpwn/dpwn_test.rb",
    "test/markdpwn_test.rb"
  ]
  s.homepage = "http://github.com/pwnall/markdpwn".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.10".freeze
  s.summary = "HTML-formats text documents such as Markdown, textile, and source code".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pygments.rb>.freeze, [">= 1.1.2"])
      s.add_runtime_dependency(%q<asciidoctor>.freeze, [">= 1.5.5"])
      s.add_runtime_dependency(%q<github-markup>.freeze, [">= 1.6.0"])
      s.add_runtime_dependency(%q<redcarpet>.freeze, [">= 3.4.0"])
      s.add_runtime_dependency(%q<RedCloth>.freeze, [">= 4.3.2"])
      s.add_runtime_dependency(%q<org-ruby>.freeze, [">= 0.9.12"])
      s.add_runtime_dependency(%q<creole>.freeze, [">= 0.5.0"])
      s.add_runtime_dependency(%q<wikicloth>.freeze, [">= 0.8.3"])
      s.add_development_dependency(%q<minitest>.freeze, [">= 5.4.1"])
      s.add_development_dependency(%q<yard>.freeze, [">= 0.9.9"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.3.5"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 2.3.5"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0.14.1"])
    else
      s.add_dependency(%q<pygments.rb>.freeze, [">= 1.1.2"])
      s.add_dependency(%q<asciidoctor>.freeze, [">= 1.5.5"])
      s.add_dependency(%q<github-markup>.freeze, [">= 1.6.0"])
      s.add_dependency(%q<redcarpet>.freeze, [">= 3.4.0"])
      s.add_dependency(%q<RedCloth>.freeze, [">= 4.3.2"])
      s.add_dependency(%q<org-ruby>.freeze, [">= 0.9.12"])
      s.add_dependency(%q<creole>.freeze, [">= 0.5.0"])
      s.add_dependency(%q<wikicloth>.freeze, [">= 0.8.3"])
      s.add_dependency(%q<minitest>.freeze, [">= 5.4.1"])
      s.add_dependency(%q<yard>.freeze, [">= 0.9.9"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.3.5"])
      s.add_dependency(%q<jeweler>.freeze, [">= 2.3.5"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0.14.1"])
    end
  else
    s.add_dependency(%q<pygments.rb>.freeze, [">= 1.1.2"])
    s.add_dependency(%q<asciidoctor>.freeze, [">= 1.5.5"])
    s.add_dependency(%q<github-markup>.freeze, [">= 1.6.0"])
    s.add_dependency(%q<redcarpet>.freeze, [">= 3.4.0"])
    s.add_dependency(%q<RedCloth>.freeze, [">= 4.3.2"])
    s.add_dependency(%q<org-ruby>.freeze, [">= 0.9.12"])
    s.add_dependency(%q<creole>.freeze, [">= 0.5.0"])
    s.add_dependency(%q<wikicloth>.freeze, [">= 0.8.3"])
    s.add_dependency(%q<minitest>.freeze, [">= 5.4.1"])
    s.add_dependency(%q<yard>.freeze, [">= 0.9.9"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.3.5"])
    s.add_dependency(%q<jeweler>.freeze, [">= 2.3.5"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0.14.1"])
  end
end

